# Empty main_bg keeps the terminal's transparency.
theme[main_bg]=""
theme[main_fg]="#eeeeee"
theme[title]="#cc0000"
theme[hi_fg]="#ffbf00"
theme[selected_bg]="#2a0000"
theme[selected_fg]="#ffbf00"
theme[inactive_fg]="#444444"
theme[proc_misc]="#cc0000"

theme[cpu_box]="#cc0000"
theme[mem_box]="#cc0000"
theme[net_box]="#cc0000"
theme[proc_box]="#cc0000"
theme[div_line]="#330000"

theme[temp_start]="#7bd88f"
theme[temp_mid]="#ffbf00"
theme[temp_end]="#ff4444"

theme[cpu_start]="#550000"
theme[cpu_mid]="#cc0000"
theme[cpu_end]="#ff4444"

theme[mem_start]="#332200"
theme[mem_mid]="#ffbf00"
theme[mem_end]="#ffdc80"

theme[net_box]="#cc0000"
theme[upload_start]="#330000"
theme[upload_mid]="#cc0000"
theme[upload_end]="#ff4444"

theme[download_start]="#332200"
theme[download_mid]="#ffbf00"
theme[download_end]="#ffdc80"
